### PR TITLE
singularity instructions

### PR DESCRIPTION
**Pull request by jpata**
Added instructions on how to compile singularity image.

### CODE REVIEW

**Comment by jpata** [comment]
@vlimant can we merge? @thongonary @zhangzc11 were also interested in using singularity.

**Comment by jpata** [comment]
I also added a pytorch image as an example and a simply way of deploying the images to users. Have a look!

**Comment by vlimant** [comment]
should we merge this in @jpata

**Comment by jpata** [comment]
yes

**Comment by thongonary** [comment]
I need sudo permission to `make`. Can it be granted?

**Pull request merged**
