### PR TITLE
add port for Thong

### PR DESCRIPTION
**Pull request by thongonary**

### CODE REVIEW

**Comment by thongonary** [comment]
@jpata Thanks for merging. Can you please sync this to the gpu cluster as well? I still receive error:

```
[E 08:40:56.902 NotebookApp] Exception while loading config file /bigdata/shared/Software/gpuservers/jupyter/jupyter_notebook_config_S.py
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/bigdata/shared/Software/gpuservers/jupyter/jupyter_notebook_config_S.py", line 293, in <module>
        c.NotebookApp.port = json.loads(open('/bigdata/shared/Software/gpuservers/jupyter/ports').read())[os.getenv('USER')]
    KeyError: 'qnguyen'
```

**Comment by jpata** [comment]
just wait, it is synced every 10min.

**Comment by thongonary** [comment]
1 hour passed and it's still not there...

**Comment by thongonary** [comment]
It for sure doesn't sync every 10 mins. Cron job broken?

**Comment by jpata** [comment]
turns out it's not under puppet, @vlimant you need to sync manually using your method.

**Pull request merged**
