### PR TITLE
Torch geometric, tf2/keras

### PR DESCRIPTION
**Pull request by jpata**
Added torch_geometric & friends in `over_edge.singularity` for GNN training @jmduarte
Also updated the anaconda-based cupy image used for the Hmm analysis.

### CODE REVIEW

**Comment by jpata** [comment]
Hold on - TF2 breaks keras...

**Comment by jpata** [comment]
Fixed now - ready to merge.

**Comment by vlimant** [comment]
over_edge is actually only an example. 

> pip3 install torch_geometric torch_sparse torch_scatter torch_cluster

should be added to the edge recipe, possibly with a version, unless @jmduarte needs tf2.0

**Comment by vlimant** [comment]
I cannot modify your branch @jpata can you please change it.

**Comment by jpata** [comment]
ok, makes sense. did the change! unfortunately I can't seem to test, as compiling the `cutting_edge.singularity` fails with an unrelated error on login-1:

```
FATAL:   container creation failed: unable to copy files to container fs: while copying /opt/openmpi-3.1.0 to /storage/user/jpata/sbuild/sbuild-644101789/fs/opt/openmpi-3.1.0: exit status 1: /bin/cp: cannot stat '/opt/openmpi-3.1.0': No such file or directory
FATAL:   While performing build: while running engine: exit status 255
```

**Pull request merged**
